### PR TITLE
Update main.js to include color randomization

### PR DESCRIPTION
**Pull request by neuroradiology**
create menu_color function in order to

- add a "randomize colors" button to the UI
- randomize the colors of every cell when the button is clicked

of note: re-generating the cells by using other aspects of the UI will revert all cells to the default color (gray).

### CODE REVIEW

**Comment by neuroradiology** [comment]
One other line needs to be added to main.js, between line 381 and 382:

`    menu_color(          grid.get_div({width:180,height:120}))`

I tried to make this all one PR, but I'm new to this and only got the new function in it.

I'll try to do it more efficiently next time.

**Review by wassfila — APPROVED** [review]
ok, so added a new menu menu_color, but actually not yet called from main I can add that, I'll first accept this PR

**Comment by wassfila** [comment]
It's working, after my last commit c901de9 to call ifrom the main congratulations, well done and thank ;)
image

**Comment by wassfila** [comment]
Use the second link though, as it's automatically updated the first one needs manual update to get last version
https://websvg.github.io/voronoi/

If you have more ideas or questions we can chat on discord https://discord.gg/wCxpAX8TQk it's a small community of those I know and we collaborate on such small projects.

**Pull request merged**
